version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend

  frontend-db:
    container_name: frontend-db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: stroamdb
      POSTGRES_USER: stroamuser
      POSTGRES_PASSWORD: stroam
  
  frontend-redis:
    container_name: frontend-redis
    restart: always
    image: redis:latest
  
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./frontend:/code
    ports:
      - "8000:8000"
    depends_on:
      - frontend-db
      - frontend-redis
    links:
      - catalog
  
  catalog:
    container_name: catalog
    restart: always
    build: ./catalog
    volumes:
      - ./catalog:/app
    ports:
      - "4000:4000"

  authserver:
    container_name: authserver
    restart: always
    build: ./authentication/authserver
    volumes:
      - ./authentication/authserver:/app
    ports:
      - "3000:3000"

  authclient:
    container_name: authclient
    restart: always
    build: ./authentication/authclient
    volumes:
      - ./authentication/authclient:/app
    ports:
      - "3200:4200"